"""autenticacao: papel do usuario e sessoes

Revision ID: 7c04a41962ca
Revises: 7282dc61e08d
Create Date: 2026-07-12 22:24:18.479745

Adiciona a camada de autenticacao: `usuarios.papel` (autorizacao por papel,
hoje so USER) e a tabela `sessoes_usuario` (uma linha por refresh token
emitido - suporta multiplas sessoes simultaneas por usuario e torna
logout/revogacao reais, ja que o refresh token em si nao e um JWT
auto-contido, e sim um segredo opaco cuja validade depende inteiramente
desta tabela).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c04a41962ca'
down_revision: Union[str, None] = '7282dc61e08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('revogado_em', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('nome_dispositivo', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_usuario_token_hash'), 'sessoes_usuario', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessoes_usuario_usuario_id'), 'sessoes_usuario', ['usuario_id'], unique=False)
    # server_default garante que a coluna NOT NULL possa ser adicionada
    # mesmo se a tabela ja tiver linhas (usuarios existentes viram 'USER').
    #
    # Deploy Postgres (2026-07-21, docs/analise-arquitetural-deploy-prealfa.md):
    # `op.add_column` sozinho (fora de `create_table`) NAO dispara os hooks
    # de DDL que criam o tipo nativo automaticamente no Postgres - so
    # `create_table` faz isso. Sem o `.create()` explicito abaixo, o
    # Postgres levanta `UndefinedObject: type "tipopapel" does not exist`
    # (confirmado rodando esta migration contra um Postgres real). No
    # SQLite, `Enum.create()`/`.drop()` sao no-op (dialeto sem tipo nativo),
    # entao o mesmo codigo funciona sem nenhum `if` de dialeto.
    papel_enum = sa.Enum('USER', name='tipopapel')
    papel_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'usuarios',
        sa.Column('papel', papel_enum, nullable=False, server_default='USER'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'papel')
    sa.Enum(name='tipopapel').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_sessoes_usuario_usuario_id'), table_name='sessoes_usuario')
    op.drop_index(op.f('ix_sessoes_usuario_token_hash'), table_name='sessoes_usuario')
    op.drop_table('sessoes_usuario')
    # ### end Alembic commands ###
